# Generated by Django 4.1 on 2022-08-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_coin"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="coin", new_name="churu",),
    ]
