# Generated by Django 4.1 on 2022-08-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_rename_coin_post_churu"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="sub_content",),
    ]
