# Generated by Django 4.0.3 on 2022-08-10 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='coin',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='star',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
