# Generated by Django 4.1 on 2022-08-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="image", field=models.TextField(),
        ),
    ]
