# Generated by Django 4.0.3 on 2022-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='coin',
            new_name='churu',
        ),
        migrations.AddField(
            model_name='profile',
            name='churu_charging',
            field=models.IntegerField(default=0),
        ),
    ]
