# Generated by Django 4.1 on 2022-08-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_coin_profile_churu_profile_churu_charging"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="star",),
    ]
